### ISSUE TITLE
Ok, my head is exploding

### ISSUE THREAD

**Issue by jlagarespo** [unrealorg/Unreal-Kernel#1]
I know this isn't even rellevant, but this gives me headache... does any of you guys know why github consideres ``data/kernel_data.inc`` a php file?
I know github algorythms for finding what language a file is written in are not always 100% accurate, but this literraly triggers me.
If i don't solve it i will end up adding garbage assembly code for github to consider it assembly, and that is ofc not a good thing...

**Comment by JL2210** [comment]
That's because it's closely formatted to PHP. Add some lines and the `.text` section and it'll be recognized as assembly.
