### ISSUE TITLE
Need to fix the fat "drivers" in the boot file...

### ISSUE THREAD

**Issue by jlagarespo** [unrealorg/Unreal-Kernel#2]
It is a total mess...
I don't even know where to start.
If someone could help that would be appreciated :) (i warn you, you won't be able to fix it...)

**Comment by JL2210** [comment]
Where are the FAT drivers located?

**Comment by jlagarespo** [comment]
To be honest this project is now discontinued, as It was way to messy and unmaintanable, I am trying to work on newer stuff for now. I don't think I will ever end up fixing those "divers", if we can even call them like so.

**Comment by jlagarespo** [comment]
https://github.com/unrealorg/Unreal-Kernel#warning-this-project-is-unmaintained-and-private-stuff-is-going-on-in-the-background-this-is-just-the-backup-for-my-old-crappy-kernel-i-might-never-publish-the-new-stuff-or-i-might-do-it-be-aware-that-this-code-is-old-and-noobish-and-dont-take-it-as-an-example-of-how-to-code-warning
